# Generated by Django 4.2 on 2023-05-25 19:13

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Affects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Damage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disassemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shareable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300, null=True)),
                ('cooldown', models.CharField(max_length=100, null=True)),
                ('manacost', models.CharField(max_length=100, null=True)),
                ('details', jsonfield.fields.JSONField(blank=True, null=True)),
                ('ability_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.abilitytype')),
                ('affects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.affects')),
                ('damage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.damage')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image_url', models.ImageField(upload_to='photos/items')),
                ('description', models.CharField(max_length=200)),
                ('lore_description', models.CharField(blank=True, max_length=200)),
                ('cost', models.CharField(max_length=100, null=True)),
                ('sell_value', models.CharField(max_length=100, null=True)),
                ('bonus', models.CharField(max_length=300, null=True)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.availability')),
                ('disassemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.disassemble')),
                ('recipe', models.ManyToManyField(blank=True, to='item.item')),
                ('shareable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.shareable')),
                ('type_global', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.typeglobal')),
                ('type_specific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.typespecific')),
            ],
        ),
    ]
