# Generated by Django 4.2 on 2023-05-12 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Disassemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shareable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='photos/items')),
                ('description', models.CharField(max_length=100)),
                ('lore_description', models.CharField(max_length=100)),
                ('type_global', models.CharField(max_length=100)),
                ('type_specific', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('sell_value', models.CharField(max_length=100)),
                ('bonus', models.CharField(max_length=100)),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.availability')),
                ('disassemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.disassemble')),
                ('shareable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.shareable')),
            ],
        ),
    ]
