# Generated by Django 4.2 on 2023-05-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='need_recipe',
            field=models.BooleanField(default=False),
        ),
    ]
