# Generated by Django 4.2 on 2023-05-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_item_need_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bonus',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
