# Generated by Django 4.2 on 2023-05-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_typeglobal_alter_availability_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='bonus',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='lore_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='type_specific',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.typespecific'),
        ),
    ]
