# Generated by Django 4.2 on 2023-05-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_alter_item_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemability',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
