# Generated by Django 4.2 on 2023-05-28 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_alter_itemability_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.itemability'),
        ),
    ]
