# Generated by Django 4.2 on 2023-05-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_alter_item_bonus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cost',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sell_value',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
