# Generated by Django 4.2 on 2023-05-28 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_item_ability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemability',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item.item'),
        ),
    ]
