# Generated by Django 4.2 on 2023-05-12 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_cost_alter_item_sell_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bonus',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
