# Generated by Django 4.2 on 2023-05-03 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('complexity', models.IntegerField()),
                ('image_url_small', models.ImageField(upload_to='photos/heroes')),
                ('image_url_large', models.ImageField(upload_to='photos/heroes')),
                ('health', models.CharField(max_length=50)),
                ('mana', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('strength_increase', models.CharField(max_length=50)),
                ('agility', models.CharField(max_length=50)),
                ('agility_increase', models.CharField(max_length=50)),
                ('intelligence', models.CharField(max_length=50)),
                ('intelligence_increase', models.CharField(max_length=50)),
                ('damage', models.CharField(max_length=50)),
                ('attack_delay', models.CharField(max_length=50)),
                ('attack_range', models.CharField(max_length=50)),
                ('flight_speed', models.CharField(max_length=50)),
                ('armor', models.CharField(max_length=50)),
                ('magic_resistance', models.CharField(max_length=50)),
                ('move_speed', models.CharField(max_length=50)),
                ('turn_speed', models.CharField(max_length=50)),
                ('vision', models.CharField(max_length=50)),
                ('talent_left_10', models.CharField(max_length=100)),
                ('talent_right_10', models.CharField(max_length=100)),
                ('talent_left_15', models.CharField(max_length=100)),
                ('talent_right_15', models.CharField(max_length=100)),
                ('talent_left_20', models.CharField(max_length=100)),
                ('talent_right_20', models.CharField(max_length=100)),
                ('talent_left_25', models.CharField(max_length=100)),
                ('talent_right_25', models.CharField(max_length=100)),
                ('attack_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.attacktype')),
                ('primary_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hero.primarystat')),
            ],
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to='', verbose_name='photos/abilities')),
                ('generic_details', models.TextField()),
                ('specific_details', models.TextField()),
                ('cooldown', models.CharField(max_length=50)),
                ('mana_cost', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hero.hero')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hero.abilitytype')),
            ],
        ),
    ]
