# Generated by Django 4.2 on 2023-04-20 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttackType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('complexity', models.IntegerField()),
                ('image_url_small', models.ImageField(upload_to='photos/small')),
                ('image_url_large', models.ImageField(upload_to='photos/large')),
                ('health', models.CharField(max_length=50)),
                ('mana', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('strength_increase', models.CharField(max_length=50)),
                ('agility', models.CharField(max_length=50)),
                ('agility_increase', models.CharField(max_length=50)),
                ('intelligence', models.CharField(max_length=50)),
                ('intelligence_increase', models.CharField(max_length=50)),
                ('damage', models.CharField(max_length=50)),
                ('attack_delay', models.CharField(max_length=50)),
                ('attack_range', models.CharField(max_length=50)),
                ('flight_speed', models.CharField(max_length=50)),
                ('armor', models.CharField(max_length=50)),
                ('magic_resistance', models.CharField(max_length=50)),
                ('move_speed', models.CharField(max_length=50)),
                ('turn_speed', models.CharField(max_length=50)),
                ('vision', models.CharField(max_length=50)),
                ('left_10', models.CharField(max_length=50)),
                ('right_10', models.CharField(max_length=50)),
                ('left_15', models.CharField(max_length=50)),
                ('right_15', models.CharField(max_length=50)),
                ('left_20', models.CharField(max_length=50)),
                ('right_20', models.CharField(max_length=50)),
                ('left_25', models.CharField(max_length=50)),
                ('right_25', models.CharField(max_length=50)),
                ('attack_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hero.attacktype')),
                ('primary_stat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hero.primarystat')),
            ],
        ),
    ]
