# Generated by Django 4.2 on 2023-05-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='image_url',
            field=models.ImageField(upload_to='photos/abilities'),
        ),
    ]
