# Generated by Django 4.2 on 2023-04-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='AttackType',
            new_name='HeroAttackType',
        ),
        migrations.RenameModel(
            old_name='PrimaryStat',
            new_name='HeroPrimaryStat',
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_url_large',
            field=models.ImageField(upload_to='photos/heroes'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='image_url_small',
            field=models.ImageField(upload_to='photos/heroes'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='left_10',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='left_15',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='left_20',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='left_25',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='right_10',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='right_15',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='right_20',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hero',
            name='right_25',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('image_url', models.ImageField(upload_to='', verbose_name='photos/abilities')),
                ('generic_details', models.TextField()),
                ('specific_details', models.TextField()),
                ('cooldown', models.CharField(max_length=50)),
                ('mana_cost', models.CharField(max_length=50)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hero.abilitytype')),
            ],
        ),
    ]
