# Generated by Django 4.2 on 2023-05-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_alter_ability_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='mana_cost',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
