# Generated by Django 4.2 on 2023-04-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0002_abilitytype_rename_attacktype_heroattacktype_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroAttackType',
            new_name='AttackType',
        ),
        migrations.RenameModel(
            old_name='HeroPrimaryStat',
            new_name='PrimaryStat',
        ),
    ]
