# Generated by Django 4.2 on 2023-05-06 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0003_alter_ability_cooldown_alter_ability_mana_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cosmetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='photos/cosmetics')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hero.hero')),
            ],
        ),
    ]
