# Generated by Django 4.2 on 2023-05-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0004_cosmetic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ability',
            name='cooldown',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ability',
            name='mana_cost',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
