# Generated by Django 4.2 on 2023-05-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hero', '0006_availability_disassemble_shareable_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='item',
            name='disassemble',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shareable',
        ),
        migrations.DeleteModel(
            name='Availability',
        ),
        migrations.DeleteModel(
            name='Disassemble',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Shareable',
        ),
    ]
